summon bat ~-5 ~ ~0 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-4 ~ ~-3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-4 ~ ~-2 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-4 ~ ~-1 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-4 ~ ~1 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-4 ~ ~2 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-4 ~ ~3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-3 ~ ~-4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-3 ~ ~-3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-3 ~ ~3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-3 ~ ~4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-2 ~ ~-4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-2 ~ ~4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-1 ~ ~-4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~-1 ~ ~4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~0 ~ ~-5 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~0 ~ ~5 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~1 ~ ~-4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~1 ~ ~4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~2 ~ ~-4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~2 ~ ~4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~3 ~ ~-4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~3 ~ ~-3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~3 ~ ~3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~3 ~ ~4 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~4 ~ ~-3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~4 ~ ~-2 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~4 ~ ~-1 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~4 ~ ~1 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~4 ~ ~2 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~4 ~ ~3 {Passengers:[{id:tnt,Fuse:120}]}
summon bat ~5 ~ ~0 {Passengers:[{id:tnt,Fuse:120}]}